version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  backend:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis:6379
      - HB_URL=http://65.108.7.125:8734
    depends_on:
      - redis
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - VITE_BACKEND_URL=/hydration-service/backend
        - VITE_HB_URL=/hydration-service/hb-node
    ports:
      - "8080:4173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis-data:

networks:
  default:
    driver: bridge