version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - private
  backend:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - HB_URL=https://hb.zoao.dev
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - private
      - public 
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        - VITE_BACKEND_URL=https://hb-hs-backend.zoao.dev
        - VITE_HB_URL=https://hb.zoao.dev
    ports:
      - "8080:4173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - public

networks:
  private:
    driver: bridge
    internal: true
  public:
    driver: bridge

volumes:
  redis-data: